[package]
name = "ark_component"
version = "0.1.0"

[dependencies]
ark_common = { path = "../ark_common" }
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros = "0.1.0"

[scripts]


<<<<<<< HEAD
[tool]

=======
>>>>>>> 2b060f9 (contracts: add `ark_component` package.)
test.workspace = true
fmt.workspace = true
[lib]
