name: ArkProject Deploy Contracts

on: workflow_dispatch

jobs:
  deploy-starknet:
    runs-on: ubuntu-latest
    name: Build & Deploy starknet contracts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Build contracts
        run: |
          cd contracts
          scarb build --workspace

      - name: Install pnpm & dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Deploy orderbook contracts
        env:
          STARKNET_NODE_URL_GOERLI: ${{ secrets.STARKNET_NODE_URL_GOERLI }}
          SOLIS_NODE_URL_GOERLI: ${{ secrets.SOLIS_NODE_URL_GOERLI }}
          STARKNET_ADMIN_ADDRESS_GOERLI: ${{ secrets.STARKNET_ADMIN_ADDRESS_GOERLI }}
          STARKNET_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PRIVATE_KEY_GOERLI }}
          STARKNET_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PUBLIC_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI }}
        run: |
          pnpm run deploy:starknet -- --starknet goerli
          pnpm run deploy:starknet:tokens -- --starknet goerli
  deploy-orderbook:
    needs: deploy-solis
    runs-on: ubuntu-latest
    name: Build & Deploy orderbook contract
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Build contracts
        run: |
          cd contracts
          scarb build --workspace

      - name: Install pnpm & dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Deploy orderbook contracts
        env:
          STARKNET_NODE_URL_GOERLI: ${{ secrets.STARKNET_NODE_URL_GOERLI }}
          SOLIS_NODE_URL_GOERLI: ${{ secrets.SOLIS_NODE_URL_GOERLI }}
          STARKNET_ADMIN_ADDRESS_GOERLI: ${{ secrets.STARKNET_ADMIN_ADDRESS_GOERLI }}
          STARKNET_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PRIVATE_KEY_GOERLI }}
          STARKNET_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PUBLIC_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI }}
          SOLIS_ADMIN_ADDRESS_GOERLI: ${{ secrets.SOLIS_ADMIN_ADDRESS_GOERLI }}
          SOLIS_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.SOLIS_ADMIN_PRIVATE_KEY_GOERLI }}
          SOLIS_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.SOLIS_ADMIN_PUBLIC_KEY_GOERLI }}
        run: |
          pnpm run deploy:solis -- --solis goerli --starknet goerli
